### ISSUE TITLE
Invoking from subdirectory

### ISSUE THREAD

**Issue by rnc** [psakar/buildmetadata-plugin-git-provider#1]
I have configured this in a sample project e.g.

```
...
              <providers>
                <provider>
                <type>org.ncl.maven.plugin.buildmetadata.data.GitScmMetadataProvider</type>
                <properties>
                  <readLocalGitRepositoryInfo>true</readLocalGitRepositoryInfo>
                  <removeDomainFromScmConnectionHostname>true</removeDomainFromScmConnectionHostname>
                </properties>
            </provider>
            </providers>
          </configuration>
        </execution>
      </executions>
      <dependencies>
        <dependency>
          <groupId>org.ncl</groupId>
          <artifactId>buildmetadata-plugin-git-provider</artifactId>
          <version>1.0-SNAPSHOT</version>
        </dependency>
      </dependencies>
    </plugin>
```

but invoking the build from a submodule gives

```
[ERROR] Failed to execute goal de.smartics.maven.plugin:buildmetadata-maven-plugin:1.6.1:provide-buildmetadata (build-metadata) on project jest-common: Execution build-metadata of goal de.smartics.maven.plugin:buildmetadata-maven-plugin:1.6.1:provide-buildmetadata failed: Can not read url of remote origin from git config /home/rnc/Work/Jest/jest/jest-common/./.git/config - File '/home/rnc/Work/Jest/jest/jest-common/./.git/config' does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.smartics.maven.plugin:buildmetadata-maven-plugin:1.6.1:provide-buildmetadata (build-metadata) on project jest-common: Execution build-metadata of goal de.smartics.maven.plugin:buildmetadata-maven-plugin:1.6.1:provide-buildmetadata failed: Can not read url of remote origin from git config /home/rnc/Work/Jest/jest/jest-common/./.git/config - File '/home/rnc/Work/Jest/jest/jest-common/./.git/config' does not exist
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution build-metadata of goal de.smartics.maven.plugin:buildmetadata-maven-plugin:1.6.1:provide-buildmetadata failed: Can not read url of remote origin from git config /home/rnc/Work/Jest/jest/jest-common/./.git/config - File '/home/rnc/Work/Jest/jest/jest-common/./.git/config' does not exist
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.IllegalArgumentException: Can not read url of remote origin from git config /home/rnc/Work/Jest/jest/jest-common/./.git/config - File '/home/rnc/Work/Jest/jest/jest-common/./.git/config' does not exist
        at org.ncl.maven.plugin.buildmetadata.data.GitScmMetadataProvider$GitScmConnectionLookup.getConnection(GitScmMetadataProvider.java:192)
        at org.ncl.maven.plugin.buildmetadata.data.GitScmMetadataProvider.getConnection(GitScmMetadataProvider.java:106)
        at org.ncl.maven.plugin.buildmetadata.data.GitScmMetadataProvider.loadConnectionInfo(GitScmMetadataProvider.java:84)
        at org.ncl.maven.plugin.buildmetadata.data.GitScmMetadataProvider.provideBuildMetaData(GitScmMetadataProvider.java:68)
        at de.smartics.maven.plugin.buildmetadata.AbstractBuildMojo.provideBuildMetaData(AbstractBuildMojo.java:515)
        at de.smartics.maven.plugin.buildmetadata.BuildMetaDataMojo.createBuildProperties(BuildMetaDataMojo.java:529)
        at de.smartics.maven.plugin.buildmetadata.BuildMetaDataMojo.execute(BuildMetaDataMojo.java:499)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
Caused by: java.io.FileNotFoundException: File '/home/rnc/Work/Jest/jest/jest-common/./.git/config' does not exist
        at org.ncl.maven.plugin.buildmetadata.data.GitScmMetadataProvider$GitScmConnectionLookup.readTextFileToList(GitScmMetadataProvider.java:212)
        at org.ncl.maven.plugin.buildmetadata.data.GitScmMetadataProvider$GitScmConnectionLookup.getConnection(GitScmMetadataProvider.java:173)
        ... 27 more
```

**Comment by psakar** [comment]
Does not make to much sense to me to build project from submodule.
I can try to find project root dir and read the info from there, but I'm not sure if it is possible. I can add configuration option to specify relative path where to look.

**Comment by rnc** [comment]
What I mean is it should not cause a project build failure if a developer has invoked the build from a submodule.

**Comment by psakar** [comment]
now I understand. I will fix it.
