### ISSUE TITLE
groupId incompatibility

### ISSUE THREAD

**Issue by rnc** [psakar/buildmetadata-plugin-git-provider#2]
Adding this provider to https://github.com/release-engineering/pom-manipulation-ext fails as that has a groupId of com.redhat.rcm.maven.plugin not de.smartics.maven.plugin

```
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:164)
        ... 20 more
Caused by: java.lang.NoClassDefFoundError: de/smartics/maven/plugin/buildmetadata/data/AbstractMetaDataProvider
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:389)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at com.redhat.rcm.maven.plugin.buildmetadata.data.MetaDataProviderBuilder.create(MetaDataProviderBuilder.java:117)
        at com.redhat.rcm.maven.plugin.buildmetadata.data.MetaDataProviderBuilder.build(MetaDataProviderBuilder.java:106)
        at com.redhat.rcm.maven.plugin.buildmetadata.AbstractBuildMojo.provideBuildMetaData(AbstractBuildMojo.java:380)
        at com.redhat.rcm.maven.plugin.buildmetadata.BuildMetaDataMojo.createBuildProperties(BuildMetaDataMojo.java:588)
        at com.redhat.rcm.maven.plugin.buildmetadata.BuildMetaDataMojo.execute(BuildMetaDataMojo.java:553)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: de.smartics.maven.plugin.buildmetadata.data.AbstractMetaDataProvider
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        ... 42 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by psakar** [comment]
I'll check it
